### ISSUE TITLE
Add readme badges

### ISSUE THREAD

**Issue by nirs** [oVirt/userstorage#18]
Good example is:
https://github.com/nirs/pytest-threadleak

Using RST format but it should be easy to convert to markdown.
We can also use https://shields.io to generate the markdown.

**Comment by krupalitrivedi** [comment]
Hello! I would like to give this a go! The badges that need to be added are for the tech-stack, right? If I am understand it correctly, I would like if you can assign the task to me :)

**Comment by nirs** [comment]
@krupalitrivedi that would be awesome!

I think the example from pytest-threadleak is good.

**Comment by nirs** [comment]
Closed by #25
